FROM golang:1.22 AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY main.go .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o plugin

FROM gcr.io/distroless/base-debian12
COPY --from=build /app/plugin /plugin
ENTRYPOINT ["/plugin"]