[build-system]
requires = ['setuptools>=61.0', 'wheel']
build-backend = 'setuptools.build_meta'

[project]
name = 'bwe-prod'
version = '0.1.0'
description = 'Bird Watchers Emporium'
requires-python = '>=3.13'
license = 'MIT'
authors = [
    {name = 'Liam Barstad', email = 'liambarstad@gmail.com'}
]

dependencies = [
    'pydantic',
    'pydantic-settings',
    'fastapi',
    'structlog',
    'uvicorn',
    'httpx',
    'langchain',
    'langgraph',
    'langchain-community',
    'langchain-neo4j',
    'langchain-openai',
    'neo4j==5.28.1'
]

[project.optional-dependencies]
dev = [
]

[project.scripts]
bwe = 'main:main'

[tool.setuptools]
packages = ['agents', 'nodes', 'tools', 'utils']
py-modules = ['config', 'main', 'state']

[tool.black]
line-length = 100
target-version = ['py313']
include = '\.pyi?$'

[tool.mypy]
python_version = '3.13'
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true
